### ISSUE TITLE
New Hugo install, errors loading lanyon

### ISSUE THREAD

**Issue by RichardDooling** [tummychow/lanyon-hugo#2]
On Mac OSX Mavericks, if I do

hugo server --theme=lanyon --buildDrafts --watch

ERROR: 2014/09/30 Rendering error: template: theme/post/single.html:5:47: executing "theme/post/single.html" at <.Site.Params.DateFor...>: invalid value; expected string

ERROR: 2014/09/30 Rendering error: template: theme/index.html:10:53: executing "theme/index.html" at <.Site.Params.DateFor...>: invalid value; expected string

**Comment by dopplesoldner** [comment]
Hi, I am facing the same problem. I added the `"DateForm"="ANSIC"` to my `config.toml` file but it doesn't work still. Is there anything else I should do?

Thanks.

**Comment by tummychow** [comment]
The thing is that `ANSIC` is a Go constant that happens to equal a valid date/time format string. It's not a valid string in and of itself. You need to set DateForm to the value of `ANSIC`, ie `"Mon Jan _2 15:04:05 2006"`.

**Comment by Code-Vortex** [comment]
how we should fix `<.Site.Params.DateFor...>: invalid value; expected string` ??

**Comment by tummychow** [comment]
What's in your `config.json` or equivalent?

**Comment by Code-Vortex** [comment]
config.toml
```
baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "My Blog"
```

**Comment by tummychow** [comment]
You need a `DateForm` key in there, eg `DateForm = "Jan 2 2006"`. Take a look at the `config.json` in this repository.

Btw PRs are welcome to set a default dateform in the layouts, but I don't use Hugo anymore so making this easier is really not a priority for me.

**Comment by mxcl** [comment]
I added this (`DateForm = "Jan 2 2006"`) to my `config.toml`, restarted the server and nothing is fixed. I tried the other values here too.

**Comment by tummychow** [comment]
what's the error message you're seeing and what's the full content of your config file?

**Comment by mxcl** [comment]
It was the same error message*, `config.toml`:

```toml
baseurl = "http://promisekit.org/"
languageCode = "en-us"
title = "PromiseKit"
PygmentsCodeFences = true 
DateForm = "Mon Jan _2 15:04:05 2006"
```

* `ERROR: 2014/09/30 Rendering error: template: theme/post/single.html:5:47: executing "theme/post/single.html" at <.Site.Params.DateFor...>: invalid value; expected string`

**Comment by tummychow** [comment]
Ah, `DateForm` needs to be under `params`, not the top level. Try:

```toml
baseurl = "http://promisekit.org/"
languageCode = "en-us"
title = "PromiseKit"
PygmentsCodeFences = true 

[params]
DateForm = "Mon Jan _2 15:04:05 2006"
```
